# Generated by Django 3.0.8 on 2022-12-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_schedule',
        ),
    ]
